### ISSUE TITLE
bug: windows 11 LoveRun not working

### ISSUE THREAD

**Issue by jacknicklenson** [S1M0N38/love2d.nvim#2]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Windows 11

### Describe the bug

running :LoveRun command does nothing. Love is on my PATH, i can run love and it launches default project. Lua language server is running.

### Steps To Reproduce

1. run :LoveRun

### Expected Behavior

Should launch project

**Comment by jacknicklenson** [comment]
Here is the  image. After i press Enter, nothing happens. I have looked up the task manager to whether it launched in the background but it didnt launched in background as well, so nothing happened.

![image](https://github.com/S1M0N38/love2d.nvim/assets/90291236/e9c76400-e6f2-43ad-b73a-1ff3a4cf3a7f)

**Comment by jacknicklenson** [comment]
If I Drag & Drop my project folder onto love.exe, it launches successfully.

**Comment by jacknicklenson** [comment]
init.lua love section:

```lua
  require('lspconfig').lua_ls.setup{}
  require'love2d'.setup{
    path_to_love_bin = "C:/Program Files/LOVE/love.exe",
    path_to_love_library = "",
    restart_on_save = false,
  }
```

.luarc.json:

```json
  {
    "runtime.version": "Lua 5.1",
    "color.mode": "SemanticEnhanced",
    "hint.enable": true,
    "hint.setType": true,
    "IntelliSense.traceBeSetted": true,
    "IntelliSense.traceFieldInject": true,
    "IntelliSense.traceLocalSet": true,
    "IntelliSense.traceReturn": true,
    "runtime.special": {
        "love.filesystem.load": "loadfile"
    },
    "workspace.library": [
        "${3rd}/love2d/library"
    ]
  }
```

**Comment by jacknicklenson** [comment]
If i run with `:!love.exe .`, it works:

![image](https://github.com/S1M0N38/love2d.nvim/assets/90291236/00ae7752-f779-4a36-8454-64e4a11a446c)

**Comment by S1M0N38** [comment]
I'm not on Windows, so I can't reproduce your setup, but my guess is that `path_to_love_bin` isn't pointing to the right location.

The `love.exe` is launched by `vim.fn.jobstart` at [this line](https://github.com/S1M0N38/love2d.nvim/blob/2e3f1841622973f48b592baf3fe7f6c8e2039cc3/lua/love2d/init.lua#L39). Maybe if `love.exe` is already in your $PATH, you could try setting `path_to_love_bin="love.exe"`.

By the way, does Windows use `/` or `\` as the path separator?

**Comment by jacknicklenson** [comment]
setting the `path_to_love_bin="love.exe"` solved the problem, thanks <3

**Comment by pumachen** [comment]
For anyone encounter the same problem, go to love2d.nvim/lua/love2d/job.lua:54 add a new line "pty = true," to vim.fn.jobstart second parameter. That should solve the problem
