### ISSUE TITLE
bug:  LSP autostart

### ISSUE THREAD

**Issue by nathanaelcunningham** [S1M0N38/love2d.nvim#4]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

MacOS 14.6.1

### Describe the bug

Is there a way to get the lsp to autostart without having to run the game?

### Steps To Reproduce

i read the documentation and dont see a way to autoattach the lsp on lua file load.

### Expected Behavior

Provide way to attach to lua_ls

**Comment by S1M0N38** [comment]
Hi, sorry for the late response.

> Is there a way to autostart the LSP without running the game?

Yes, you can load `love2d.nvim` on the `VeryLazy` event instead of waiting for the first use of the `LoveRun` command. If you're using `lazy.nvim`, you can update your configuration like this:

```lua
{
  "S1M0N38/love2d.nvim",
  event = "VeryLazy",
  opts = {},
}
```
